#stages:
#  - build
#
#build:
#  tags:
#    - ios-builder
#  stage: build
#  script:
#    - ./.ci/build.sh
#  only:
#    - merge_requests

stages:
  - test1
  - test2

test1:
  tags:
    - ios-builder
  stage: test1
  script:
    - echo "test1"
    - echo $CI_COMMIT_TITLE
  rules:
    - if: $CI_COMMIT_TITLE =~ /-ios/
    - if: $CI_COMMIT_TITLE =~ /-mac/



test2:
  tags:
    - ios-builder
  stage: test2
  script:
    - echo "test2"
    - echo $CI_COMMIT_TITLE
  rules:
    - if: $CI_COMMIT_TITLE =~ /-android/
    - if: $CI_COMMIT_TITLE =~ /-win/
