#stages:
#  - build
#
#build:
#  tags:
#    - ios-builder
#  stage: build
#  script:
#    - ./.ci/build.sh
#  only:
#    - merge_requests

stages:
  - arch
  - test1

  
variables:
  AndroidPackageOnWindow: 1

test1:
  tags:
    - ios-builder
  stage: test1
  script:
    - echo "test1"
    - echo $TDSCICD
    - echo $CI_COMMIT_TITLE
    - python3 xdsdk_build.py $CI_COMMIT_TITLE
  rules:
    - if: $CI_COMMIT_TITLE =~ /-ios/
    - if: $CI_COMMIT_TITLE =~ /-android/
    - if: $CI_COMMIT_TITLE =~ /-win/
    - if: $CI_COMMIT_TITLE =~ /-mac/
    - if: $CI_COMMIT_TITLE =~ /-mobile/
    - if: $CI_COMMIT_TITLE =~ /-pc/
    - if: $CI_COMMIT_TITLE =~ /-all/



arch_plugins:
  tags:
    - ios-builder
  stage: arch
  script:
    - echo "arch"
    - echo $CI_COMMIT_TITLE
    - python3 archive_plugins.py
  rules:
    - if: $CI_COMMIT_TITLE =~ /-arch/
  artifacts:
    name: XDSDK_UE_$CI_COMMIT_SHORT_SHA
    paths:
      - "*/XDSDK/Plugins.zip"
    expire_in: 1 week
