#stages:
#  - build
#
#build:
#  tags:
#    - ios-builder
#  stage: build
#  script:
#    - ./.ci/build.sh
#  only:
#    - merge_requests

stages:
  - arch_plugins
  - product_app

  
variables:
  AndroidPackageOnWindow: 1

product_app:
  tags:
    - ios-builder
    - tds-packager-win
  stage: product_app
  script:
    - echo "product_app"
    - echo $CI_COMMIT_TITLE
    - python3 package_upload.py $CI_COMMIT_TITLE
  rules:
    - if: $CI_COMMIT_TITLE =~ /-ios/
    - if: $CI_COMMIT_TITLE =~ /-android/
    - if: $CI_COMMIT_TITLE =~ /-win/
    - if: $CI_COMMIT_TITLE =~ /-mac/
    - if: $CI_COMMIT_TITLE =~ /-mobile/
    - if: $CI_COMMIT_TITLE =~ /-pc/
    - if: $CI_COMMIT_TITLE =~ /-all/



arch_plugins:
  tags:
    - ios-builder
  stage: arch_plugins
  script:
    - echo "arch"
    - echo $CI_COMMIT_TITLE
    - python3 archive_plugins.py
  rules:
    - if: $CI_COMMIT_TITLE =~ /-arch/
  artifacts:
    name: XDSDK_UE_$CI_COMMIT_SHORT_SHA
    paths:
      - Product/Plugins.zip
    expire_in: 1 week
